# Generated by Django 4.2.13 on 2024-06-04 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0003_alter_news_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 6, 4, 12, 28, 11, 568024, tzinfo=datetime.timezone.utc)),
        ),
    ]
