# Generated by Django 4.2.13 on 2024-06-05 12:16

import datetime
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('NewsApp', '0006_customer_staff_alter_news_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyNewUser',
            fields=[
            ],
            options={
                'ordering': ('username',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 6, 5, 12, 16, 19, 484645, tzinfo=datetime.timezone.utc)),
        ),
    ]
